### ISSUE TITLE
What's the rationale?

### ISSUE THREAD

**Issue by agzam** [viesti/cypress-clojurescript-preprocessor#12]
I wanted to try out Cypress with my shadow-cljs based project. I found this library, but it doesn't seem to say why one should consider using this approach instead of simply adding another build section in shadow-cljs.edn.

What are the benefits?

Readme states:
> generates a shadow-cljs.edn configuration file with a build for each test file

Why does it have to have a separate build for every test file? What if there are hundreds of them?

This project seems very nicely done, and maybe it should become the de facto standard way of integrating Cypress into Clojurescript projects; maybe it already is, as I noted - I'm a noob and never used Cypress before.

I think adding a paragraph explaining the pros & cons of this approach would be helpful for newbies like me.

**Comment by viesti** [comment]
Thank you for such nice feedback! :)

You pointed out very good questions that made me think again about this a bit dormant experimentation of a project that I made :D. 

> why one should consider using this approach instead of simply adding another build section in shadow-cljs.edn.

Very good point! This is how I originally hacked Cypress to work with ClojureScript. I remember trying out cljs.main and figwheel-main but there was some trouble with them and shadow-cljs managed to generate a bundle that Cypress could load.

I thought that this would be it but then started to think that the way you use Cypress is that you just start writing out a test file, and Cypress just automatically picks it up and reloads the test file when it's changed. I thought that it's kind of (embarrassingly?) manual work to remember to create a new shadow-cljs build config configure Cypress to read the output directory of the build (since it doesn't know what to do with a .cljs) file.

So then I learned about preprocessors and remembered the [mention in Cypress docs about ClojureScript](https://docs.cypress.io/api/plugins/preprocessors-api) :) 

> A preprocessor could transpile your file from another language (CoffeeScript or ClojureScript) or from a newer version of JavaScript (ES2017).

So I set on a journey to see if I could make a preprocessor that runs shadow-cljs on the background and the user could then just keep on adding test files and writing tests and they just show up in Cypress.

> Why does it have to have a separate build for every test file? What if there are hundreds of them?

This I'm not exactly sure about, but how Cypress works is that it loads a test file into the test runner, so in ClojureScript we also have to output a JavaScript file in the end. I think the usual way in JVM/Clojure and ClojureScript is to have all (or some) tests in a discoverable (bundled into a single file in JavaScript or just files on the classpath in JVM) but to just execute some (or all) of them. I didn't figure out how to generate multiple files in shadow-cljs any other way than defining multiple builds. Not sure how shadow-cljs scales with hundreds of builds though :D

I guess the above, with a bit of cleaning, could be put into the readme to explain the rationale, if it feels sane to you? :)

Thank you again on the feedback :)

**Comment by agzam** [comment]
Sorry if I sounded like I was complaining. I posted the issue while trying to figure out how everything works. Despite the apparent complexity of all the required "plumbing", I was surprised how simple it is to set this up and start writing tests. I like this project, and I admit, I was hesitant and couldn't decide, should I try it or rather set up a separate build in shadow-cljs.edn.

If you can come up with a nice paragraph that could work as a "marketing bait," I think it would lure more users and (hopefully) collaborators too. This project is great - it solves a specific problem and does it in a straightforward, undogmatic, flexible manner. It seems googling: "shadow-cljs cypress" or "clojurescript cypress" already pops up its home page, and that's awesome.
